version: "3.9"

services:
  allocare-web:
    build: .
    container_name: allocare-web
    environment:
      SECRET_KEY: change-this-for-production
      DATABASE_PATH: data/allocare.db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: allocare.auth.events
      RABBITMQ_PATIENT_QUEUE: allocare.patient.admission
      RABBITMQ_BED_QUEUE: allocare.bed.updates
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    volumes:
      - allocare-data:/app/data

  allocare-consumer:
    build: .
    container_name: allocare-consumer
    command: python consumer.py
    environment:
      DATABASE_PATH: data/allocare.db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - rabbitmq
    volumes:
      - allocare-data:/app/data

  allocare-file-monitor:
    build: .
    container_name: allocare-file-monitor
    command: python file_monitor.py
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - rabbitmq
    volumes:
      - allocare-data:/app/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: allocare-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  allocare-data:
